# Build do Angular
FROM node:22 AS build

WORKDIR /app

COPY FrontEnd/package*.json ./

RUN npm ci

COPY FrontEnd/ .

RUN npm run build

# Runtime
FROM nginx:alpine

COPY deploy/nginx.front.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx","-g","daemon off;"]