name: Deploy Lessie Backend

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

  workflow_dispatch:

jobs:

  build-and-deploy:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore Backend/src/Api/Lessie.Api.csproj

    - name: Build
      run: dotnet build Backend/src/Api/Lessie.Api.csproj --configuration Release --no-restore


    - name: Validate WebDeploy secrets
      shell: pwsh
      env:
        WEBDEPLOY_USER: ${{ secrets.WEBDEPLOY_USER }}
        WEBDEPLOY_PASSWORD: ${{ secrets.WEBDEPLOY_PASSWORD }}
      run: |
        if ([string]::IsNullOrWhiteSpace($env:WEBDEPLOY_USER)) {
          throw "WEBDEPLOY_USER está vazio ou não existe neste repositório."
        }
    
        if ([string]::IsNullOrWhiteSpace($env:WEBDEPLOY_PASSWORD)) {
          throw "WEBDEPLOY_PASSWORD está vazio ou não existe neste repositório."
        }
    
        Write-Host "Secrets encontrados."
        Write-Host "Tamanho do usuário: $($env:WEBDEPLOY_USER.Length)"
        Write-Host "Tamanho da senha: $($env:WEBDEPLOY_PASSWORD.Length)"



    - name: Publish
      run: dotnet publish Backend/src/Api/Lessie.Api.csproj `
            --configuration Release `
            --output ./publish `
            --no-build




    - name: Deploy via WebDeploy
      shell: pwsh
      run: |
        dotnet publish Backend/src/Api/Lessie.Api.csproj `
          --configuration Release `
          --no-build `
          -p:PublishProfile=IISProfile `
          -p:UserName="wlsolutions-002" `
          -p:Password="${{ secrets.WEBDEPLOY_PASSWORD }}" `
          -p:AllowUntrustedCertificate=True
