name: Deploy ASP.NET via WebDeploy

on:
  schedule:
    - cron: "0 1 * * *"   # 22:00 Brasil

  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    # Verifica se houve commit nas últimas 24h
    - name: Check if there were changes
      id: check_changes
      shell: pwsh
      run: |
        $changes = git log --since="24 hours ago" --oneline
        if ($changes) {
          echo "changed=true" >> $env:GITHUB_OUTPUT
        }
        else {
          echo "changed=false" >> $env:GITHUB_OUTPUT
        }

    # Só builda se houve mudança
    - name: Setup .NET
      if: steps.check_changes.outputs.changed == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      if: steps.check_changes.outputs.changed == 'true'
      run: dotnet restore

    - name: Build project
      if: steps.check_changes.outputs.changed == 'true'
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      if: steps.check_changes.outputs.changed == 'true'
      run: dotnet publish --configuration Release --output ./publish --no-build

    - name: Deploy via WebDeploy
      if: steps.check_changes.outputs.changed == 'true'
      run: dotnet publish `
            -c Release `
            -p:PublishProfile=IISProfile `
            -p:UserName="${{ secrets.WEBDEPLOY_USER }}" `
            -p:Password="${{ secrets.WEBDEPLOY_PASSWORD }}"            
